### ISSUE TITLE
Android 10 supportsAuthentication is false

### ISSUE THREAD

**Issue by MichalNemec** [eaceto/flutter_local_authentication#2]
Tested device: Xiaomi Mi A2
enrolled with finger + pin
getting always false, permission with USE_BIOMETRIC added in all three manifests.
in app info i see, that it uses biometric

**Comment by eaceto** [comment]
Hi, sorry for the delay, I have been very very busy and I could catch up with this.  Could you figure out what was the problem or you still need help?
Thanks!
Ezequiel.-

**Comment by MichalNemec** [comment]
Hello, not really. 
Its showing on SM-S908U but cannot see it on xiaomi mi a2.
Which else permissions it needs if its not problem on your side?

**Comment by eaceto** [comment]
Hi, I’ll find out if there is something related to this Xiaomi device.

do you have a log(cat) output where May be an exception is happening?

**Comment by MichalNemec** [comment]
I didnt find way back when i was testing it any exception. in the app it says false.

**Comment by eaceto** [comment]
Hello @MichalNemec I believe this issue is fixed in version 1.0.0. Would you mind testing it? Thanks very much
